### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by apratimankur** [Navybits/meteor-roundsliderui#1]
Uncaught TypeError: $(...).roundSlider is not a function(…)

**Comment by hstabbal** [comment]
Hi Apratim, 

Have you fixed it? If yes, would you mind if we merge our work ?

---- On Thu, 17 Mar 2016 19:59:11 +0200 Apratim Ankur &lt;notifications@github.com&gt;wrote ---- 

Closed #1.
